# Generated by Django 3.1.1 on 2020-10-04 11:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('link', models.URLField()),
                ('perc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('view', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('dm', "don't miss"), ('wt', "what's tranding")], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BlogNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Gadgets', 'Gadgets'), ('Lifestyle', 'Lifestyle')], default='Fashion', max_length=10)),
                ('events', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('status', models.CharField(choices=[('home', 'home'), ('blog', 'blog')], default='blog', max_length=20)),
                ('position', models.CharField(choices=[('dm', "don't miss"), ('wt', "what's tranding")], default='dm', max_length=2)),
                ('body', ckeditor.fields.RichTextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ManyToManyField(to='blog.Tag')),
            ],
            options={
                'verbose_name': 'Blog New',
                'verbose_name_plural': 'Blog News',
            },
        ),
    ]
