# Generated by Django 3.1.2 on 2020-10-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201004_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideo',
            name='events',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
