# Generated by Django 3.1.2 on 2020-10-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideo',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
