# Generated by Django 3.1.2 on 2020-10-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogvideo',
            name='events',
        ),
    ]
